### PR TITLE
Remove the layout cache and rename layout -> trackInfo.

### LINKED ISSUE #603: Writing D88 with `ibm` format is broken
```
Error: LAYOUT: no sectors in sector definition!
```

### PR DESCRIPTION
**Pull request by tdaede**
The layout cache is busted and seems not worth the effort.

Fixes #603.

### CODE REVIEW

**Comment by davidgiven** [comment]
This one I'm not sure about. This did actually seem to significantly improve performance (although I'll admit I never actually bothered to benchmark it). What problems were you seeing?

**Comment by tdaede** [comment]
Without this, if I write a d88 file with the `ibm` format, it only writes one sector onto every track.

**Comment by tdaede** [comment]
Also, I'm not seeing anything that clears the cache if you write 2 successive disks (e.g. via the GUI).

**Comment by davidgiven** [comment]
I'm sorry, I dropped this one.

The cache is actually cleared by magic via calling `Environment::reset()`, which will call `clear()` on all globals wrapped in the `Local<>` construct. However, if you're actually seeing problems then it clearly doesn't work, and as it's just a performance booster, let's disable it.

**Pull request merged**
