### PR TITLE
Fix various doc typos

### PR DESCRIPTION
**Pull request by JohnVeness**
Hi, I have fixed a few typos in documentation files only. Thanks :)

### CODE REVIEW

**Comment by JohnVeness** [comment]
There is also something wrong in disk-c64.md in the line:
`1581 disks are just another version of the standard B Just do:`
But I'm not quite sure what the correct text is.

**Comment by davidgiven** [comment]
Wow --- that embarrassing, particularly as my mother was an English teacher... let me know when it's ready and I'll merge. Thanks!

**Comment by JohnVeness** [comment]
Haha, no worries! It's mostly very good, I'm just nit-picking really :)

I think I'm done for the time being, other than noticing that on cowlark.com there is an oddity where an extra Acorn ADFS entry appears in the navigation, but I can't see where to fix that.
image

**Comment by davidgiven** [comment]
The last will be an issue with my CMS --- will fix. Thank you very much for doing this!

**Pull request merged**
