### PR TITLE
add dsk format which is basically diskcopy minus the 0x54 byte header

### PR DESCRIPTION
**Pull request by ladyada**
most mac emulators / computers dont like diskcopy format - they prefer dsk there's a converter but it would save a step if dsk's were emitted :)
see https://www.bigmessowires.com/dc2dsk.c
not sure if i did this right, and its a lil hacky, since we don't crop the file, but it does work!

image

### CODE REVIEW

**Comment by ladyada** [comment]
btw mac400 works just fine too :)

image

image

**Comment by davidgiven** [comment]
Actually, the existing image writer can handle these --- it just needs to be configured properly. I've done this and it's in the `macdsk` branch. PTAL and see if it works for you?

**Comment by ladyada** [comment]
ooh didnt look there, ill fetch and check now

**Comment by ladyada** [comment]
verified reading is good with that branch, testing writing next

**Pull request closed without merging**
