### PR TITLE
Imd reader

### PR DESCRIPTION
**Pull request by wybren1971**
Finally got around to adept the IMD reader to read an IMD image en set the protoconfiguration and be able to write it to physical media

### CODE REVIEW

**Comment by wybren1971** [comment]
please have a look at the code as i am not that familiar with proto. but it works fine with my tests

**Comment by davidgiven** [comment]
All looks good to me, but just to check: did you mean to update the hplif770 format at the same time?

**Comment by wybren1971** [comment]
Yes, because I found some problems with it. And this works better. 

I used this imdreader to write back an imd image to disk for my logic analyzer.

Thanks Wybren

**Comment by davidgiven** [comment]
Excellent --- just checking. Thank you very much for doing this!

**Pull request merged**
