### PR TITLE
Miscellaneous bugfixes.

### PR DESCRIPTION
**Pull request by davidgiven**
Put back the standard makefile targets.
Fixes: #722 

The GUI can open flux and image files for writing.
Fixes: #721 

Make the build system saner.
Fixes: #701 

Also, strip out the broken tpi stuff in favour of something much simpler (and more working).

### CODE REVIEW

**Comment by misterblack1** [comment]
Hi David, unfortunately the GUI disk writing still isn't working for me with this latest build. (fb9f7fe from 45 minutes ago)  Same error on picking any disk image to write.  

I tested with 1440k IBM format images and a Mac 800k disk image. 

image

Windows 10.0.19045.3570 + Greaseweazle

**Comment by davidgiven** [comment]
Huh. I've just tried it and it works here. Can you describe your exact process?

**Comment by misterblack1** [comment]
I made a short video:
https://youtu.be/b4I3EudYpTU

The error is the same with IBM disks -- hadn't tried others but I assume it's the same with all. As you mentioned before, the command line work fine.

**Comment by chironb** [comment]
I, too, I still seeing this issue with the GUI program. I'm using the 2-day old release, so I know it's the latest version. I'm getting the same "cannot open file" error. I've also tried installing it as administrator and I've run the program as administrator. Same error. Just like the video. Doesn't seem to matter what formats I select or what file I choose. 

I also tried the FluxEngine command-line version. I got this output: 

.\fluxengine.exe write C:\Users\micro\Desktop\System3.2_Journal.Mac400.img

[libprotobuf ERROR ../../src/google/protobuf/text_format.cc:335] Error parsing text-format ConfigProto: 1:3: Message type "ConfigProto" has no field named "LK".

Error: couldn't load external config proto

I hope that helps!

**Comment by chironb** [comment]
In addition to my earlier comment, I have a little bit of possibly useful observations. In my comment I listed the problem with the command-line version and saw it was related to the google/protobuf/ stuff. But in the GUI version the error seems to be generated here: 
            wxMessageBox(e.message, "Error", wxOK | wxICON_ERROR);
            if (_state == STATE_WRITING_WORKING)
                SetState(STATE_WRITING_FAILED);
That seems to imply that auto filename = wxFileSelector works but then 
            if (filename.empty())
                return;
returns, which gets us to the final error message. 

So it seems like there is some problem with the library used to either get the file from Windows 10 (in my case) or a problem with something that maybe is in google/protobuf but I'm not sure. 

BUT!!!!

When I choose a file called Untitled.png it gives me the error: 
unrecognized image filename
C:\Users\micro\Desktop\Untitled.png

So... I took an floppy disk image file and renamed it to Untitled.png just to see what would happen. It gives the same error as the actual file that was an actual .png file. 

This is also true with files like .exe or .jpg in that whenever I try to open them, it clearly gets a full path and filename but then looks at the extension and decided it's not an actual image filename. Because I would guess that if it were reading inside the file it would figure out that the wrongly named disk image file would have worked. 

Clearly it's getting as far as analyzing the filename to determine if it's a valid image, but then failing when it tries to start reading the actual file. 

I'm using Greaseweazle with FluxEngine and reading works just fine. But this seems more like an issue with FluxEngine and local file access and does not seem to even get as far as accessing Greaseweazle, since the drive doesn't make any noise or get accesses in any way and the error message seems to be presented instantly. 

I hope this helps even if it's maybe too much information!

**Comment by chironb** [comment]
One more detail: I can format a disk using the format button in the FluxEngine GUI.

**Pull request merged**
